#!/usr/bin/env bash

function config_vim() {
  sudo apt-get remove --purge vim vim-runtime vim-gnome vim-tiny vim-gui-common
  sudo apt-get install liblua5.1-dev luajit libluajit-5.1 python-dev ruby-dev libperl-dev libncurses5-dev libatk1.0-dev libx11-dev libxpm-dev libxt-dev
  sudo rm -rf /usr/local/share/vim /usr/bin/vim
  git clone https://github.com/vim/vim
  cd vim
  git pull && git fetch
  #In case Vim was already installed
  cd src
  make distclean
  cd ..

  ./configure \
    --enable-multibyte \
    --enable-perlinterp=dynamic \
    --enable-rubyinterp=dynamic \
    --with-ruby-command=/usr/bin/ruby \
    --enable-pythoninterp=dynamic \
    --with-python-config-dir=/usr/lib/python2.7/config-arm-linux-gnueabihf \
    --enable-python3interp \
    --with-python3-config-dir=/usr/lib/python3.5/config-3.5m-arm-linux-gnueabihf \
    --enable-luainterp \
    --with-luajit \
    --enable-cscope \
    --enable-gui=auto \
    --with-features=huge \
    --with-x \
    --enable-fontset \
    --enable-largefile \
    --disable-netbeans \
    --with-compiledby="yourname" \
    --enable-fail-if-missing

  make && sudo make install
}

function is_docker_nexus3() {
  docker ps -f "ancestor=sonatype/nexus3:atest" --format "{{.ID}}: {{.Command}} {{.Image}}"  | grep sonatype/nexus3:atest > /dev/null
}

function install_nexus() {
  docker create volume nexus-data
  docker run -d -p 8081:8081 --restart always --name nexus -v nexus-data:/nexus-data sonatype/nexus3
}

# A function that Download assets from github
function list_github_releases() {
   curl -s https://api.github.com/repos/${repo}/releases/latest | grep "browser_download_url"
   # TODO  list_github_releases ginuerzh/gost
   # TODO  list_github_releases dandavison/delta
}


function is_raspberry_pi_os_64() {
  grep "Raspberry Pi" /proc/device-tree/model &> /dev/null && [ "aarch64" = $(uname -m) ]
}

GOST_BIN=/usr/local/bin/gost

function download_gost() {
  echo "Downloading gost to ${GOST_BIN}"
  curl -L "https://github.com/ginuerzh/gost/releases/download/v2.11.1/gost-linux-armv8-2.11.1.gz" | gunzip -c | sudo tee  ${GOST_BIN} > /dev/null
  sudo chmod +x ${GOST_BIN}
}


function download_git_delta() {
  local pkg_tmp="$(mktemp)"
  curl -o ${pkg_tmp} -L "https://github.com/dandavison/delta/releases/download/0.7.1/git-delta_0.7.1_arm64.deb" && sudo dpkg -i ${pkg_tmp}
  rm -f ${pkg_tmp}
}

GOST_SERVICE=/etc/systemd/system/gost.service
function generate_gost_service() {
  if [ -f "${GOST_SERVICE}" ]; then
    echo "Gost systemd service exists."
    return 0
  fi
  if [ -z "${GOST_PROXY}" ]; then
    echo "Please specify a GOST_PROXY!"
    exit 1
  fi
  sudo tee ${GOST_SERVICE} >/dev/null <<EOF
[Unit]
Description=Gost Proxy
After=network.target
Wants=network.target

[Service]
Type=simple
ExecStart=${GOST_BIN} -L "socks://0.0.0.0:1080" -L "http://0.0.0.0:8080" -F "${GOST_PROXY}"
Restart=always

[Install]
WantedBy=multi-user.target
EOF
}

if is_raspberry_pi_os_64; then
  # XXX Raspberry Pi OS 64bit, maybe extends to other platform later
  dpkg -l git-delta &> /dev/null || {
    download_git_delta
  }

  [ -f ${GOST_BIN} ] || {
      download_gost || {
      echo "Failed to downnload gost!" 
      exit 1
    }
  }
  generate_gost_service && sudo systemctl start gost
fi



if ! [ -d "$HOME/.oh-my-zsh" ]; then
  echo "Install oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended || {
    echo "Install oh-my-zsh failed, exiting..."
    exit 1
  }
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${HOME}/.oh-my-zsh/custom/themes/powerlevel10k || {
    echo "Install power10k failed, exiting..."
    exit 1
  }
fi

function install_go_proxy() {
  go env -w GOPROXY="http://${WSL_HOST}:8081/repository/go/"
  go env -w GOSUMDB="sum.golang.org http://${WSL_HOST}:8081/repository/gosum/"
}
