plugin:
  #get all resources in a namespace using the krew get-all plugin
  get-all-namespace:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - namespaces
    command: sh
    background: false
    args:
    - -c
    - "kubectl get-all -n $NAME | less"
  get-all-other:
    shortCut: g
    confirm: false
    description: get-all
    scopes:
    - all
    command: sh
    background: false
    args:
    - -c
    - "kubectl get-all -n $NAMESPACE | less"
  debug:
    shortCut: Shift-D
    description: Add debug container
    scopes:
      - containers
    command: bash
    background: false
    confirm: true
    args:
      - -c
      - "kubectl debug -it -n=$NAMESPACE $POD --target=$NAME --image=nicolaka/netshoot:v0.11 --share-processes -- bash"
  # Leverage stern (https://github.com/stern/stern) to output logs.
  stern:
    shortCut: Ctrl-L
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
    command: stern
    background: false
    args:
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  stern-namespace:
    shortCut: Ctrl-L
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - namespaces
    command: stern
    background: false
    args:
      - -n
      - $COL-NAME
      - --context
      - $CONTEXT
      - .
  stern-deployment:
    shortCut: Ctrl-L
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - deployments
    command: stern
    background: false
    args:
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      - deployment/$NAME
