#!/usr/bin/env bash

if ! [ -d "$HOME/.oh-my-zsh" ]; then
  echo "Install oh-my-zsh"
  sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc --unattended || {
    echo "Install oh-my-zsh failed, exiting..."
    exit 1
  }
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ${HOME}/.oh-my-zsh/custom/themes/powerlevel10k || {
    echo "Install power10k failed, exiting..."
    exit 1
  }
fi
